#! /bin/sh

set -e

COMMAND=$1
DEVICE=$2
IMAGE=$3
URL=$4

ZNX_DIR=$(mktemp -d)

HELP=\
"Usage: znx COMMAND DEVICE [IMAGE] [URL | PATH]

COMMAND is one of:

  - init:
    Initializes the storage device for its further usage.
    The DEVICE parameter must be passed.

  - deploy:
    Deploys an image on a storage device.
    The image name must comply the regular expression:
    ^[[a-zA-Z0-9]_-]+/[[a-zA-Z0-9]_-]+$
    e.g. nitrux/rolling, nitrux/release_v1-01.
    The DEVICE, IMAGE and URL or PATH parameters must be
    passed. In case a URL is passed, it should point to
    a zsync file.

  - update:
    Updates an already deployed image. The image should
    have proper information in order to proceed with the
    update, otherwise it fails.
    The DEVICE and IMAGE parameters must be passed.

  - rollback:
    Revert an update of an image. If the image hadn't been
    updated previously, it will fail.
    The DEVICE and IMAGE parameters must be passed.

  - clean:
    Removes the backup that is created during an update.
    The DEVICE and IMAGE parameters must be passed.

  - remove:
    Removes all data associated to the specified image,
    as well as the image.
    The DEVICE and IMAGE parameters must be passed.

  - list:
    Shows a list of the installed images.

  - help:
    Show this help.

"


# Helper functions.

error () {
	printf "znx: \e[31mError:\e[0m $@\n" >& 2
	exit 1
}

_mount () {
	for d in $DEVICE*; do

		blkid $d | grep -q ZNX_DATA &&
			mount $d $ZNX_DIR ||
			error "Unable to mount $d! Exiting now."

	done

	mountpoint -q $ZNX_DIR ||
		error "Device isn't being managed by znx. You must initialize it first."

}

clean () {
	cd /
	while mountpoint -q $ZNX_DIR; do
		umount -f $ZNX_DIR
	done
	rm -rf $ZNX_DIR
}

trap clean EXIT HUP INT TERM


# Sanity checks.

[ $# -eq 0 ] &&
	error "No command given!"

[ $(id -u) -ne 0 ] &&
	error "You are not the super user."

[ ! -b $DEVICE ] &&
	error "$DEVICE is not a block device"

printf $DEVICE | grep -q '[0-9]' &&
	error "Please provide a block device name, not a partition."

[ ! -z $IMAGE ] &&
	printf $IMAGE | grep -qE '^[[:alnum:]_-]+/[[:alnum:]_-]+$' ||
	error "The image name must match the extended regular expression: '^[[:alnum:]_-]+/[[:alnum:]_-]+$'."


# Prepare the temporary directory.

mkdir -p $ZNX_DIR


# Run the specified command.

case $COMMAND in

	init)

		[ $# -ne 2 ] &&
			error "Bad command: wrong number of arguments."

		grep -q $DEVICE /proc/mounts &&
			error "Device is mounted! Unmount it before continuing."

		PREFIX=$(dirname $(readlink -f $0))

		printf "Wiping $DEVICE. Please wait.\n"
		wipefs -af $DEVICE
		sgdisk -Z \
			-n 1::132M -t 1:EF00 -c 1:ZNX_BOOT \
			-N 2 -t 2:8300 -c 2:ZNX_DATA $DEVICE

		for d in $DEVICE*; do

			# Prepare the boot partition.

			blkid $d | grep -q ZNX_BOOT && {
				mkfs.vfat $d
				mount $d $ZNX_DIR ||
					error "Unable to mount $d! Device initialization failed."

				mkdir -p \
					$ZNX_DIR/efi/boot \
					$ZNX_DIR/boot/grub

				cp $PREFIX/grub.cfg $ZNX_DIR/boot/grub
				cp $PREFIX/bootx64.efi $ZNX_DIR/efi/boot

			}

			# Prepare the data partition.

			blkid $d | grep -q ZNX_DATA && {
				mkfs.btrfs -f $d
				mount $d $ZNX_DIR ||
					error "Unable to mount $d! Device initialization failed."

				mkdir -p \
					$ZNX_DIR/data/etc \
					$ZNX_DIR/data/home \
					$ZNX_DIR/boot_images
			}

		done

		printf "Operation successful. Device is ready.\n"

	;;

	deploy)

		[ $# -ne 4 ] &&
			error "Bad command: wrong number of arguments."

		_mount
		printf "Deploying $IMAGE.\n"

		[ -d $ZNX_DIR/boot_images/$IMAGE ] &&
			error "Deployment aborted: $IMAGE is already deployed."

		mkdir -p $ZNX_DIR/boot_images/$IMAGE

		cp $URL $ZNX_DIR/boot_images/$IMAGE || (
			cd $ZNX_DIR/boot_images/$IMAGE
			zsync $URL
		) || {
			rm -rf $ZNX_DIR/boot_images/$IMAGE
			error "Failed to deploy $IMAGE."
		}

		printf "Successfully deployed \e[32m$IMAGE\e[0m.\n"

	;;

	update)

		[ $# -ne 3 ] &&
			error "Bad command: wrong number of arguments."

		_mount
		printf "Updating $IMAGE.\n"

		cd $ZNX_DIR/boot_images/$IMAGE ||
			error "$IMAGE is not deployed."

		UPDATE_URL=$(printf $(dd if=$(printf *.iso) bs=1 skip=33651 count=512 2> /dev/null))

		zsync $UPDATE_URL ||
			error "Failed to update $IMAGE."

		printf "Successfully updated $IMAGE.\n"

	;;

	rollback)

		[ $# -ne 3 ] &&
			error "Bad command: wrong number of arguments."

		_mount
		printf "Performing rollback on $IMAGE.\n"

		cd $ZNX_DIR/boot_images/$IMAGE ||
			error "$IMAGE is not deployed."

		mv -f *.zs-old *.iso &&
			printf "Sucessfully performed rollback on $IMAGE.\n" ||
			error "Couldn't perform a rollback on $IMAGE."

	;;

	clean)

		[ $# -ne 3 ] &&
			error "Bad command: wrong number of arguments."

		_mount
		printf "Cleaning $IMAGE.\n"

		cd $ZNX_DIR/boot_images/$IMAGE ||
			error "$IMAGE is not deployed,"

		rm *.zs-old &&
			printf "Sucessfully cleaned $IMAGE.\n" ||
			error "Nothing to clean."

	;;

	remove)

		[ $# -ne 3 ] &&
			error "Bad command: wrong number of arguments."

		_mount
		check_name $IMAGE
		printf "Removing $IMAGE.\n"

		[ -d $ZNX_DIR/boot_images/$IMAGE ] ||
			error "$IMAGE is not deployed."

		rm -rf $ZNX_DIR/boot_images/$IMAGE &&
			printf "Successfully removed \e[32m$IMAGE\e[0m.\n"

	;;

	list)

		[ $# -ne 2 ] &&
			error "Bad command: wrong number of arguments."

		_mount

		cd $ZNX_DIR/boot_images

		for x in */*; do
			[ -d $x ] &&
				printf "\e[36m${x}\e[0m\n"
		done

	;;

	help )

		printf "$HELP"
	;;

	*) error "No such command '$COMMAND'.";;

esac
