#! /bin/sh

set -e

COMMAND=$1
DEVICE=$2
IMAGE=$3
URL=$4

ZNX_DIR=$(mktemp -d)


# -- Helper functions.

error () {
	echo "znx: \e[31mError:\e[0m $@" >& 2
	exit 1
}

_mount () {
	for d in $DEVICE*; do

		blkid $d | grep -q ZNX_DATA && {
			grep -q $DEVICE /proc/mounts && \
				mount -o bind $(grep $d /proc/mounts | cut -d ' ' -f 2) $ZNX_DIR || \
				mount $d $ZNX_DIR || \
				error "Unable to mount $d! Exiting now."
		}

	done

	mountpoint -q $ZNX_DIR || \
		error "Device isn't being managed by znx. You must initialize it first."

}

clean () {
	cd /
	while mountpoint -q $ZNX_DIR; do
		umount -f $ZNX_DIR
	done
	rm -rf $ZNX_DIR
}

trap clean EXIT HUP INT TERM


# -- Sanity checks.

[ $# -eq 0 ] && \
	error "No command given!"

[ $(id -u) -ne 0 ] && \
	error "You are not the super user."

[ ! -b $DEVICE ] && \
	error "$DEVICE is not a block device"

echo $DEVICE | grep -q '[0-9]' && \
	error "Please provide a block device name, not a partition."


# -- Prepare the temporary directory.

mkdir -p $ZNX_DIR


# -- Run the specified command.

case $COMMAND in

	init)

		[ $# -ne 2 ] && \
			error "Bad command: wrong number of arguments."

		grep -q $DEVICE /proc/mounts && \
			error "Device is mounted! Unmount it before continuing."

		PREFIX=$(dirname $(readlink -f $0))

		echo "Wiping $DEVICE. Please wait."
		sgdisk -Zo $DEVICE \
			-n 1::16M -t 1:EF00 -c 1:ZNX_BOOT \
			-N 2 -t 2:8300 -c 2:ZNX_DATA $DEVICE

		for d in $DEVICE*; do

			# -- Prepare the boot partition.

			blkid $d | grep -q ZNX_BOOT && {
				mkfs.vfat $d
				mount $d $ZNX_DIR || \
					error "Unable to mount $d! Device initialization failed."

				mkdir -p $ZNX_DIR/efi/boot
				mkdir -p $ZNX_DIR/boot

				grub-mkimage -C xz -O x86_64-efi \
					-o $ZNX_DIR/efi/boot/bootx64.efi \
					-d $PREFIX/grub-modules \
					boot linux search normal configfile \
					part_gpt btrfs fat iso9660 loopback \
					test keystatus gfxmenu regexp probe \
					efi_gop efi_uga all_video gfxterm font \
					echo read ls cat png jpeg halt reboot

				mkdir -p $ZNX_DIR/boot/grub
				cp $PREFIX/grub.cfg $ZNX_DIR/boot/grub

			}

			# -- Prepare the data partition.

			blkid $d | grep -q ZNX_DATA && {
				mkfs.btrfs -f $d
				mount $d $ZNX_DIR || \
					error "Unable to mount $d! Device initialization failed."

				mkdir -p $ZNX_DIR/boot_images
				mkdir -p \
					$ZNX_DIR/data/config \
					$ZNX_DIR/data/user
			}

		done

		echo "Operation successful. Device is ready."

	;;

	deploy)

		[ $# -ne 4 ] && \
			error "Bad command: wrong number of arguments."

		echo $IMAGE | grep -qE '^[[:alnum:]_-]+/[[:alnum:]_-]+$' || \
			error "The image name must match the extended regular expression: '^[[:alnum:]_-]+/[[:alnum:]_-]+$'."

		_mount
		echo "Deploying $IMAGE."

		[ -d $ZNX_DIR/boot_images/$IMAGE ] && \
			error "Deployment aborted: $IMAGE is already deployed."

		mkdir -p $ZNX_DIR/boot_images/$IMAGE

		cp $URL $ZNX_DIR/boot_images/$IMAGE || (
			cd $ZNX_DIR/boot_images/$IMAGE
			zsync $URL
		) || {
			rm -rf $ZNX_DIR/boot_images/$IMAGE
			error "Failed to deploy $IMAGE."
		}

		echo "Successfully deployed \e[32m$IMAGE\e[0m."

	;;

	update)

		[ $# -eq 3 -o $# -eq 4 ] || \
			error "Bad command: wrong number of arguments."

		_mount
		echo "Updating $IMAGE."

		cd $ZNX_DIR/boot_images/$IMAGE || \
			error "$IMAGE is not deployed."

		UPDATE_URL=$(echo $(dd if=*.iso bs=1 seek=33651 count=512 2> /dev/null))

		zsync ${URL:-$UPDATE_URL} || \
			error "Failed to access ${URL:-$UPDATE_URL}."

		echo "Successfully updated $IMAGE."

	;;

	rollback)

		[ $# -ne 3 ] && \
			error "Bad command: wrong number of arguments."

		_mount
		echo "Performing rollback on $IMAGE."

		cd $ZNX_DIR/boot_images/$IMAGE || \
			error "$IMAGE is not deployed."

		mv -f *.zs-old *.iso && \
			echo "Sucessfully performed rollback on $IMAGE." || \
			error "Couldn't perform a rollback on $IMAGE."

	;;

	clean)

		[ $# -ne 3 ] && \
			error "Bad command: wrong number of arguments."

		_mount
		echo "Cleaning $IMAGE."

		cd $ZNX_DIR/boot_images/$IMAGE || \
			error "$IMAGE is not deployed,"

		rm -rf *.zs-old && \
			echo "Sucessfully cleaned $IMAGE."

	;;

	remove)

		[ $# -ne 3 ] && \
			error "Bad command: wrong number of arguments."

		_mount
		echo "Removing $IMAGE."

		[ -d $ZNX_DIR/boot_images/$IMAGE ] || \
			error "$IMAGE is not deployed."

		rm -rf $ZNX_DIR/boot_images/$IMAGE && \
			echo "Successfully removed \e[32m$IMAGE\e[0m."

	;;

	list)

		[ $# -ne 2 ] && \
			error "Bad command: wrong number of arguments."

		_mount

		cd $ZNX_DIR/boot_images

		for x in */*; do
			[ -f $x ] && \
				echo -e "\e[36m${x}\e[0m"
		done

	;;

	*) error "No such command '$COMMAND'.";;

esac
